// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdelgvwpdeybsnpzhzxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkZWxndndwZGV5YnNucHpoenhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNzY3NTYsImV4cCI6MjA3Mjk1Mjc1Nn0.T7vVZfj5S8P700G16-81uCiB5xIhvX_a7jkc0HPgC4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});